### ISSUE TITLE
Phan support 

### ISSUE THREAD

**Issue by behram** [ojs/ojs#1633]
### Describe issue
___________________
we can support phan code analyzer

### Related Links
-----------------
https://github.com/etsy/phan

| Q                  | A
| -------------      | ---
| Branch/Tag?        | "master" 
| Bug?               | no
| New feature?       | yes

**Comment by hmert** [comment]
it died very fast.

```
➜  ojs git:(master) ✗ phan -p --directory .
Phan\Exception\IssueException in /usr/local/Cellar/phan/0.6/src/Phan/AST/ContextNode.php:562
Stack trace:
#0 /usr/local/Cellar/phan/0.6/src/Phan/Analysis/AssignmentVisitor.php(140): Phan\AST\ContextNode->getProperty('id')
#1 /usr/local/Cellar/phan/0.6/src/Phan/AST/Visitor/Element.php(111): Phan\Analysis\AssignmentVisitor->visitList(Object(ast\Node))
#2 /usr/local/Cellar/phan/0.6/src/Phan/AST/Visitor/KindVisitorImplementation.php(22): Phan\AST\Visitor\Element->acceptKindVisitor(Object(Phan\Analysis\AssignmentVisitor))
#3 /usr/local/Cellar/phan/0.6/src/Phan/Analysis/PostOrderAnalysisVisitor.php(116): Phan\AST\Visitor\KindVisitorImplementation->__invoke(Object(ast\Node))
#4 /usr/local/Cellar/phan/0.6/src/Phan/AST/Visitor/Element.php(39): Phan\Analysis\PostOrderAnalysisVisitor->visitAssign(Object(ast\Node))
#5 /usr/local/Cellar/phan/0.6/src/Phan/AST/Visitor/KindVisitorImplementation.php(22): Phan\AST\Visitor\Element->acceptKindVisitor(Object(Phan\Analysis\PostOrderAnalysisVisitor))
#6 /usr/local/Cellar/phan/0.6/src/Phan/BlockAnalysisVisitor.php(124): Phan\AST\Visitor\KindVisitorImplementation->__invoke(Object(ast\Node))
#7 /usr/local/Cellar/phan/0.6/src/Phan/AST/Visitor/KindVisitorImplementation.php(42): Phan\BlockAnalysisVisitor->visit(Object(ast\Node))
#8 /usr/local/Cellar/phan/0.6/src/Phan/AST/Visitor/Element.php(39): Phan\AST\Visitor\KindVisitorImplementation->visitAssign(Object(ast\Node))
#9 /usr/local/Cellar/phan/0.6/src/Phan/AST/Visitor/KindVisitorImplementation.php(22): Phan\AST\Visitor\Element->acceptKindVisitor(Object(Phan\BlockAnalysisVisitor))
#10 /usr/local/Cellar/phan/0.6/src/Phan/BlockAnalysisVisitor.php(114): Phan\AST\Visitor\KindVisitorImplementation->__invoke(Object(ast\Node))
#11 /usr/local/Cellar/phan/0.6/src/Phan/AST/Visitor/KindVisitorImplementation.php(312): Phan\BlockAnalysisVisitor->visit(Object(ast\Node))
#12 /usr/local/Cellar/phan/0.6/src/Phan/AST/Visitor/Element.php(147): Phan\AST\Visitor\KindVisitorImplementation->visitStmtList(Object(ast\Node))
#13 /usr/local/Cellar/phan/0.6/src/Phan/AST/Visitor/KindVisitorImplementation.php(22): Phan\AST\Visitor\Element->acceptKindVisitor(Object(Phan\BlockAnalysisVisitor))
#14 /usr/local/Cellar/phan/0.6/src/Phan/BlockAnalysisVisitor.php(369): Phan\AST\Visitor\KindVisitorImplementation->__invoke(Object(ast\Node))
#15 /usr/local/Cellar/phan/0.6/src/Phan/BlockAnalysisVisitor.php(459): Phan\BlockAnalysisVisitor->visitClosedContext(Object(ast\Node\Decl))
#16 /usr/local/Cellar/phan/0.6/src/Phan/AST/Visitor/Element.php(115): Phan\BlockAnalysisVisitor->visitMethod(Object(ast\Node\Decl))
#17 /usr/local/Cellar/phan/0.6/src/Phan/AST/Visitor/KindVisitorImplementation.php(22): Phan\AST\Visitor\Element->acceptKindVisitor(Object(Phan\BlockAnalysisVisitor))
#18 /usr/local/Cellar/phan/0.6/src/Phan/BlockAnalysisVisitor.php(114): Phan\AST\Visitor\KindVisitorImplementation->__invoke(Object(ast\Node\Decl))
#19 /usr/local/Cellar/phan/0.6/src/Phan/AST/Visitor/KindVisitorImplementation.php(312): Phan\BlockAnalysisVisitor->visit(Object(ast\Node))
#20 /usr/local/Cellar/phan/0.6/src/Phan/AST/Visitor/Element.php(147): Phan\AST\Visitor\KindVisitorImplementation->visitStmtList(Object(ast\Node))
#21 /usr/local/Cellar/phan/0.6/src/Phan/AST/Visitor/KindVisitorImplementation.php(22): Phan\AST\Visitor\Element->acceptKindVisitor(Object(Phan\BlockAnalysisVisitor))
#22 /usr/local/Cellar/phan/0.6/src/Phan/BlockAnalysisVisitor.php(369): Phan\AST\Visitor\KindVisitorImplementation->__invoke(Object(ast\Node))
#23 /usr/local/Cellar/phan/0.6/src/Phan/BlockAnalysisVisitor.php(446): Phan\BlockAnalysisVisitor->visitClosedContext(Object(ast\Node\Decl))
#24 /usr/local/Cellar/phan/0.6/src/Phan/AST/Visitor/Element.php(55): Phan\BlockAnalysisVisitor->visitClass(Object(ast\Node\Decl))
#25 /usr/local/Cellar/phan/0.6/src/Phan/AST/Visitor/KindVisitorImplementation.php(22): Phan\AST\Visitor\Element->acceptKindVisitor(Object(Phan\BlockAnalysisVisitor))
#26 /usr/local/Cellar/phan/0.6/src/Phan/BlockAnalysisVisitor.php(114): Phan\AST\Visitor\KindVisitorImplementation->__invoke(Object(ast\Node\Decl))
#27 /usr/local/Cellar/phan/0.6/src/Phan/AST/Visitor/KindVisitorImplementation.php(312): Phan\BlockAnalysisVisitor->visit(Object(ast\Node))
#28 /usr/local/Cellar/phan/0.6/src/Phan/AST/Visitor/Element.php(147): Phan\AST\Visitor\KindVisitorImplementation->visitStmtList(Object(ast\Node))
#29 /usr/local/Cellar/phan/0.6/src/Phan/AST/Visitor/KindVisitorImplementation.php(22): Phan\AST\Visitor\Element->acceptKindVisitor(Object(Phan\BlockAnalysisVisitor))
#30 /usr/local/Cellar/phan/0.6/src/Phan/Analysis.php(358): Phan\AST\Visitor\KindVisitorImplementation->__invoke(Object(ast\Node))
#31 /usr/local/Cellar/phan/0.6/src/Phan/Phan.php(169): Phan\Analysis::analyzeFile(Object(Phan\CodeBase), './vendor/friend...')
#32 /usr/local/Cellar/phan/0.6/src/Phan/Phan.php(210): Phan\Phan::Phan\{closure}(7095, './vendor/friend...')
#33 /usr/local/Cellar/phan/0.6/src/phan.php(43): Phan\Phan::analyzeFileList(Object(Phan\CodeBase), Array)
#34 /usr/local/Cellar/phan/0.6/phan(2): require_once('/usr/local/Cell...')
#35 {main}

```
